Check if files are different
joergi/MagPiDownloader#259

diff --git a/.github/workflows/testing-magpi-regulars.yml b/.github/workflows/testing-magpi-regulars.yml
--- a/.github/workflows/testing-magpi-regulars.yml
+++ b/.github/workflows/testing-magpi-regulars.yml
@@ -91,3 +91,14 @@ jobs:
       - name: File exists
         if: steps.check_files.outputs.files_exists == 'false'
         run: exit 1
+
+      - name: "check if files are all different"
+        id: md5_files
+        shell: bash
+        run: |
+          cmp --silent regular/MagPi_1.pdf regular/MagPi_2.pdf && { echo '### ERROR: Files Are Identical! ###'; exit 1; } || true 
+          cmp --silent regular/MagPi_2.pdf regular/MagPi_50.pdf && { echo '### ERROR: Files Are Identical! ###'; exit 1; } || true
+          cmp --silent regular/MagPi_50.pdf regular/MagPi_51.pdf && { echo '### ERROR: Files Are Identical! ###'; exit 1; } || true
+          cmp --silent regular/MagPi_51.pdf regular/MagPi_52.pdf && { echo '### ERROR: Files Are Identical! ###'; exit 1; } || true
+          cmp --silent regular/MagPi_52.pdf regular/MagPi_${{ env.ISSUE_MINUS_ONE }}.pdf && { echo '### ERROR: Files Are Identical! ###'; exit 1; } || true
+          cmp --silent regular/MagPi_${{ env.ISSUE_MINUS_ONE }}.pdf regular/MagPi_${{ env.ISSUE_NUMBER }}.pdf && { echo '### ERROR: Files Are Identical! ###'; exit 1; } || true
