remove tests for hello world books
joergi/HelloWorldDownloader#12

diff --git a/.github/workflows/testing-hello-world-books.yml b/.github/workflows/testing-hello-world-books.yml
--- a/.github/workflows/testing-hello-world-books.yml
+++ b/.github/workflows/testing-hello-world-books.yml
@@ -24,33 +24,33 @@ on:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  books-powershell:
-    runs-on: windows-latest
-    steps:
-      - uses: actions/checkout@v3.5.3
-
-      - name: make folder for books
-        run: mkdir books
-        shell: bash
-
-      - name: Download Books Hello World windows
-        id: HelloWorldBooksWin
-        shell: pwsh
-        run: ./windows/downloader.ps1 -downloadUrl "https://helloworld.raspberrypi.org/books/big_book_of_pedagogy/pdf" -outputDir "books"
-
-      - name: lslah books
-        run: Get-ChildItem –path D:\a\downloader\downloader\books
-
-      - name: "Check file existence Windows special"
-        id: check_files
-        uses: andstor/file-existence-action@v2.0.0
-        with:
-          files: "books/Hello_World_The_Big_Book_of_Pedagogy.pdf"
-          fail: true
-
-      - name: File exists
-        if: steps.check_files.outputs.files_exists == 'false'
-        run: exit 1
+#  books-powershell:
+#    runs-on: windows-latest
+#    steps:
+#      - uses: actions/checkout@v3.5.3
+#
+#      - name: make folder for books
+#        run: mkdir books
+#        shell: bash
+#
+#      - name: Download Books Hello World windows
+#        id: HelloWorldBooksWin
+#        shell: pwsh
+#        run: ./windows/downloader.ps1 -downloadUrl "https://helloworld.raspberrypi.org/books/big_book_of_pedagogy/pdf" -outputDir "books"
+#
+#      - name: lslah books
+#        run: Get-ChildItem –path D:\a\downloader\downloader\books
+#
+#      - name: "Check file existence Windows special"
+#        id: check_files
+#        uses: andstor/file-existence-action@v2.0.0
+#        with:
+#          files: "books/Hello_World_The_Big_Book_of_Pedagogy.pdf"
+#          fail: true
+#
+#      - name: File exists
+#        if: steps.check_files.outputs.files_exists == 'false'
+#        run: exit 1
 
   books-bash-linux:
     runs-on: ubuntu-latest
